const serviceData = [
    {
        customerName: "John Doe",
        mobile: "9901019920",
        carModel: "Swift Dzire",
        year: "2016",
        registrationNumber: "MH04 DP 7718",
        address: "Hinjewadi",
        carColor: "Maroon",
        serviceRequired: ["Polish", "Interiors"],
        dateOfService: "07/07/2023",
        totalAmount: "8800",
        dailyWash: "no",
    },
    {
        customerName: "Sachin T",
        mobile: "8871667219",
        carModel: "Hyundai Exter",
        year: "2023",
        registrationNumber: "MH04 LO 8817",
        address: "Hadapasar",
        carColor: "White",
        serviceRequired: ["Interiors", "New Tyres"],
        dateOfService: "01/06/2023",
        totalAmount: "22300",
        dailyWash: "yes",
    },
    {
        customerName: "Praveen",
        mobile: "7899182778",
        carModel: "Venue",
        year: "2018",
        registrationNumber: "MH05 GJ 9918",
        address: "Pune",
        carColor: "Black",
        serviceRequired: ["Polish", "Interiors"],
        dateOfService: "10/04/2023",
        totalAmount: "14000",
        dailyWash: "no",
    },
    {
        customerName: "John Doe",
        mobile: "9901019920",
        carModel: "Swift Dzire",
        year: "2016",
        registrationNumber: "MH04 DP 7718",
        address: "Hinjewadi",
        carColor: "Maroon",
        serviceRequired: ["Polish", "Interiors"],
        dateOfService: "07/07/2023",
        totalAmount: "8800",
        dailyWash: "no",
    },
    {
        customerName: "Sachin T",
        mobile: "8871667219",
        carModel: "Hyundai Exter",
        year: "2023",
        registrationNumber: "MH04 LO 8817",
        address: "Hadapasar",
        carColor: "White",
        serviceRequired: ["Interiors", "New Tyres"],
        dateOfService: "01/06/2023",
        totalAmount: "22300",
        dailyWash: "yes",
    },
    {
        customerName: "Praveen",
        mobile: "7899182778",
        carModel: "Venue",
        year: "2018",
        registrationNumber: "MH05 GJ 9918",
        address: "Pune",
        carColor: "Black",
        serviceRequired: ["Polish", "Interiors"],
        dateOfService: "10/04/2023",
        totalAmount: "14000",
        dailyWash: "no",
    },
    {
        customerName: "John Doe",
        mobile: "9901019920",
        carModel: "Swift Dzire",
        year: "2016",
        registrationNumber: "MH04 DP 7718",
        address: "Hinjewadi",
        carColor: "Maroon",
        serviceRequired: ["Polish", "Interiors"],
        dateOfService: "07/07/2023",
        totalAmount: "8800",
        dailyWash: "no",
    },
    {
        customerName: "Sachin T",
        mobile: "8871667219",
        carModel: "Hyundai Exter",
        year: "2023",
        registrationNumber: "MH04 LO 8817",
        address: "Hadapasar",
        carColor: "White",
        serviceRequired: ["Interiors", "New Tyres"],
        dateOfService: "01/06/2023",
        totalAmount: "22300",
        dailyWash: "yes",
    },
    {
        customerName: "Praveen",
        mobile: "7899182778",
        carModel: "Venue",
        year: "2018",
        registrationNumber: "MH05 GJ 9918",
        address: "Pune",
        carColor: "Black",
        serviceRequired: ["Polish", "Interiors"],
        dateOfService: "10/04/2023",
        totalAmount: "14000",
        dailyWash: "no",
    },
]

export default serviceData;